// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppetofnuceulghkdnphz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZXRvZm51Y2V1bGdoa2RucGh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwOTcwNzUsImV4cCI6MjA4NDY3MzA3NX0.tq3VyeocwUnqCP4iAdEZLau5Dd1Y1pHE2pMjs8NAZnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});